// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbrjbkhxebubgegkrtje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRicmpia2h4ZWJ1YmdlZ2tydGplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMjMxMzQsImV4cCI6MjA2Mzc5OTEzNH0.xBsCPQDSfYt5g3ptyp5j6Sugq7uZXPFgD9EOUq9OGYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);